/*

 BACKGROUNDTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define BackgroundTilesBank 0

/* Super Gameboy palette 0 */
#define BackgroundTilesSGBPal0c0 6076
#define BackgroundTilesSGBPal0c1 8935
#define BackgroundTilesSGBPal0c2 6596
#define BackgroundTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BackgroundTilesSGBPal1c0 6076
#define BackgroundTilesSGBPal1c1 8935
#define BackgroundTilesSGBPal1c2 6596
#define BackgroundTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BackgroundTilesSGBPal2c0 6076
#define BackgroundTilesSGBPal2c1 8935
#define BackgroundTilesSGBPal2c2 6596
#define BackgroundTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BackgroundTilesSGBPal3c0 6076
#define BackgroundTilesSGBPal3c1 8935
#define BackgroundTilesSGBPal3c2 6596
#define BackgroundTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BackgroundTilesCGBPal0c0 30719
#define BackgroundTilesCGBPal0c1 1023
#define BackgroundTilesCGBPal0c2 15855
#define BackgroundTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define BackgroundTilesCGBPal1c0 30719
#define BackgroundTilesCGBPal1c1 381
#define BackgroundTilesCGBPal1c2 15855
#define BackgroundTilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define BackgroundTilesCGBPal2c0 30719
#define BackgroundTilesCGBPal2c1 93
#define BackgroundTilesCGBPal2c2 15855
#define BackgroundTilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define BackgroundTilesCGBPal3c0 30719
#define BackgroundTilesCGBPal3c1 23616
#define BackgroundTilesCGBPal3c2 15855
#define BackgroundTilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define BackgroundTilesCGBPal4c0 30719
#define BackgroundTilesCGBPal4c1 32549
#define BackgroundTilesCGBPal4c2 15855
#define BackgroundTilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define BackgroundTilesCGBPal5c0 30719
#define BackgroundTilesCGBPal5c1 7136
#define BackgroundTilesCGBPal5c2 15855
#define BackgroundTilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define BackgroundTilesCGBPal6c0 30719
#define BackgroundTilesCGBPal6c1 17427
#define BackgroundTilesCGBPal6c2 15855
#define BackgroundTilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define BackgroundTilesCGBPal7c0 30719
#define BackgroundTilesCGBPal7c1 1023
#define BackgroundTilesCGBPal7c2 15855
#define BackgroundTilesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char BackgroundTilesCGB[];
/* Start of tile array. */
extern unsigned char BackgroundTiles[];

/* End of BACKGROUNDTILES.H */
