/*

 TETROMINOS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define TetrominosBank 0

/* Gameboy Color palette 0 */
#define TetrominosCGBPal0c0 30719
#define TetrominosCGBPal0c1 1023
#define TetrominosCGBPal0c2 15855
#define TetrominosCGBPal0c3 0

/* Gameboy Color palette 1 */
#define TetrominosCGBPal1c0 30719
#define TetrominosCGBPal1c1 381
#define TetrominosCGBPal1c2 15855
#define TetrominosCGBPal1c3 0

/* Gameboy Color palette 2 */
#define TetrominosCGBPal2c0 30719
#define TetrominosCGBPal2c1 93
#define TetrominosCGBPal2c2 15855
#define TetrominosCGBPal2c3 0

/* Gameboy Color palette 3 */
#define TetrominosCGBPal3c0 30719
#define TetrominosCGBPal3c1 23616
#define TetrominosCGBPal3c2 15855
#define TetrominosCGBPal3c3 0

/* Gameboy Color palette 4 */
#define TetrominosCGBPal4c0 30719
#define TetrominosCGBPal4c1 32549
#define TetrominosCGBPal4c2 15855
#define TetrominosCGBPal4c3 0

/* Gameboy Color palette 5 */
#define TetrominosCGBPal5c0 30719
#define TetrominosCGBPal5c1 7136
#define TetrominosCGBPal5c2 15855
#define TetrominosCGBPal5c3 0

/* Gameboy Color palette 6 */
#define TetrominosCGBPal6c0 30719
#define TetrominosCGBPal6c1 17427
#define TetrominosCGBPal6c2 15855
#define TetrominosCGBPal6c3 0

/* CGBpalette entries. */
extern unsigned char TetrominosCGB[];
/* Start of tile array. */
extern unsigned char Tetrominos[];

/* End of TETROMINOS.H */
