/*

 TETROMINOS.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
unsigned char TetrominosCGB[] =
{
  0x00,0x01
};
/* Start of tile array. */
unsigned char Tetrominos[] =
{
  0xFF,0x00,0xFF,0x00,0xFF,0x24,0xFF,0x00,
  0xFF,0x42,0xFF,0x3C,0xFF,0x00,0x00,0xFF,
  0x7F,0x80,0x7F,0x90,0x7F,0xA4,0x7F,0xA0,
  0x7F,0xA0,0x7F,0xA4,0x7F,0x90,0x7F,0x80
};

/* End of TETROMINOS.C */
